feature/khoatgd add new brand full
jason103nguyen/HuyKhoaPhuong-ClubManager pull request #6
Opened 2021-11-14 12:13 UTC by trankhoa798

PR description:

Add feature to create new brand:

1. Update dao
2. Update service
3. Update controller

14/11/2021

2021-11-14 12:48 UTC, jason103nguyen approved these changes
Please check your code again and let's merge to main. Thanks!

2021-11-14 12:48 UTC, jason103nguyen commented on src/main/java/com/fa/training/dto/AdvertisingContractDto.java
> +	public AdvertisingContractDto transformPersistentToDto(final AdvertisingContract contract) {
I think you should be use the constructor for converting from entity to dto! What do you think about that?

2021-11-14 12:48 UTC, jason103nguyen commented on src/main/java/com/fa/training/dto/BrandDto.java
>  	public Brand dtoAsPersistent() {
Please comment the purpose of this method!

2021-11-16 04:27 UTC, MaHai1993 commented on src/main/java/com/fa/training/service/impl/BrandServiceImpl.java
> +	BrandDaoImpl brandDao;
properties MUST be private.

2021-11-16 04:27 UTC, MaHai1993 commented on src/main/java/com/fa/training/controller/BrandController.java
> +		dto.setName("Nike");
remove this hard code later

2021-11-16 04:28 UTC, MaHai1993 requested changes
Fix comment.
I help you change branch name in PR also.

2021-11-18 03:20 UTC, merged